### PR TITLE
Add monospace theme variations

### PR DESCRIPTION
**Pull request by mhkeller**
Per https://github.com/RandomFractals/vscode-data-preview/issues/196

Needs testing

### CODE REVIEW

**Comment by mhkeller** [comment]
Ah sorry about that – yes the whitespace is annoying. It's the default on my editor. May be good to throw an .editorconfig file in there. If I get some time to come back to it I can redo it to make a merge nicer. But at least you can test the functionality for now.

**Comment by RandomFractals** [comment]
don't worry about it. I did not notice before those extra spaces were there. 

Thanks for that cleanup. I'll merge it later this week.

**Comment by mhkeller** [comment]
Since the CSS comes from the perspective library, I suggested they also use monospace and there's some interesting feedback from one of the collaborators on how they're changing the codebase: https://github.com/finos/perspective/issues/1008

**Comment by RandomFractals** [comment]
yeah, I've seen their updates for new data grid setup. thanks for logging this feature request it in their repo.

**Comment by RandomFractals** [comment]
Closing this PR per comments in #196 and more info you provided in perspective repo above.

**Pull request closed without merging**
